version: "3.1"

services:
    mysql_db:
        container_name: ${MYSQL_CONTAINER_NAME}
        restart: always
        image: mysql
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./.mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            #- ./.mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
            #- ./.mysql/seed.sql:/docker-entrypoint-initdb.d/seed.sql #Seed Data Only - Optional

    mystichome:
        container_name: ${APP_CONTAINER_NAME}
        restart: always
        volumes:
            - ./.mysql/glassfish_init:/opt/glassfish7/custom:ro
            - ./src/main/java/Content:${FILE_UPLOAD_PATH}/Content
            - upload_files:${FILE_UPLOAD_PATH}
        build: .
        image: mystichome
        ports:
            - "8080:8080"
            - "4848:4848"
        environment:
            MYSQL_CONTAINER_NAME: ${MYSQL_CONTAINER_NAME}
            MYSQL_HOST: ${MYSQL_CONTAINER_NAME}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

            POOL_ENABLESSL: ${POOL_ENABLESSL}
            POOL_ALLOW_PUBLICKEY_RETRIEVAL: ${POOL_ALLOW_PUBLICKEY_RETRIEVAL}
            POOL_SERVER_TIMEZONE: ${POOL_SERVER_TIMEZONE}

            JTA_DATA_SOURCE: ${JTA_DATA_SOURCE}
            
            FILE_UPLOAD_PATH: ${FILE_UPLOAD_PATH}
        depends_on:
            - ${MYSQL_CONTAINER_NAME}

    mysql_admin:
        container_name: mysql_admin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: ${MYSQL_CONTAINER_NAME}
            PMA_USER: ${PMA_USER}
            PMA_PASSWORD: ${PMA_PASSWORD}
        depends_on:
            - ${MYSQL_CONTAINER_NAME}
    redis:
        container_name: ${REDIS_CONTAINER_NAME}
        image: redis
        restart: always
        volumes:
            - redis_data:/data
        ports:
            - "${REDIS_PORT}:6379"
        command: ["redis-server", "--appendonly", "yes"]
        depends_on:
            - ${MYSQL_CONTAINER_NAME}
            - ${APP_CONTAINER_NAME}
volumes:
    upload_files:
        driver: local
    mysql_data:
    redis_data:
        driver: local
