version: "3.1"

services:
    mysql_db:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql

    mysql_admin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql_db
            PMA_USER: ${PMA_USER}
            PMA_PASSWORD: ${PMA_PASSWORD}
        depends_on:
            - mysql_db

    mystichome:
        build: .
        image: mystichome:3.0.9.5
        ports:
            - "8080:8080"
            - "4848:4848"
        environment:
            MYSQL_HOST: mysql_db
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        depends_on:
            - mysql_db

volumes:
    mysql_data:
