version: "3.1"

services:
    mysql_db:
        container_name: mysql_db
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./.mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

    mysql_admin:
        container_name: mysql_admin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql_db
            PMA_USER: ${PMA_USER}
            PMA_PASSWORD: ${PMA_PASSWORD}
        depends_on:
            - mysql_db

    mystichome:
        container_name: mystichome
        volumes:
            - ./.mysql/glassfish_init:/opt/glassfish7/custom:ro
        build: .
        image: mystichome
        ports:
            - "8080:8080"
            - "4848:4848"
        environment:
            MYSQL_CONTAINER_NAME: ${MYSQL_CONTAINER_NAME}
            MYSQL_HOST: mysql_db
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

            POOL_ENABLESSL: ${POOL_ENABLESSL}
            POOL_ALLOW_PUBLICKEY_RETRIEVAL: ${POOL_ALLOW_PUBLICKEY_RETRIEVAL}
            POOL_SERVER_TIMEZONE: ${POOL_SERVER_TIMEZONE}

            JTA_DATA_SOURCE: ${JTA_DATA_SOURCE}
        depends_on:
            - mysql_db

volumes:
    mysql_data:
